[project]
name = "tf-idf-cls"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "jieba>=0.42.1",
    "optuna>=4.4.0",
    "plotly>=6.2.0",
    "scikit-learn>=1.6.1",
]
